### ISSUE TITLE
Add link to data on README.md

### ISSUE THREAD

**Issue by abfleishman** [pointblue/Soundscapes2Landscapes#199]
The url for the data on the readme for CNN_Bird_Species/ says TBD.  Replace with correct link

**Comment by leosalas** [comment]
Hi Abram. We are working to resolve this quickly. All the small data files are in this repository; Matt Clark is uploading the large ones to the Zenodo URI. Hopefully in the next couple of days we'll be able to open the link.

**Comment by leosalas** [comment]
Oh, I see that Matt just opened the Zenodo URI. Closing this issue now.

**Comment by abfleishman** [comment]
Thank you!  Such fast turn around!
